### ISSUE TITLE
Better time conversion

### ISSUE THREAD

**Issue by popy-dev** [caarmen/french-revolutionary-calendar#16]
Currently times are converted by being transformed into a day fraction, which is then transformed into the target time format.

This process includes many divisions, which means many floats, which means many float precision loss. This results sometimes in a loss of a second ! Ain't nobody got time for that !

I came to a similar solution : instead of gradually calculating a day ratio, the idea is to convert a time into seconds (or any lower unit if needed), then apply a ratio _seconds = seconds * SECONDS_IN_TARGET_FORMAT_BY_DAY / SECONDS_IN_SOURCE_FORMAT_BY_DAY_
and finally, convert bact this seconds count to the target time format.

This solutions means there is only one division, one float conversion, so only one imprecision.

Here is an extract of my PHP implementation if it is easier to understand.

```php
<?php


/**
 * Converts a "Time" (represented by an array of each of its constituents)
 *     from one format (defined by constituents sizes) into another format
 *     (defined by constituents sizes) using a "lower unity count ratio"
 *     calculation.
 *
 * @param array<int> $timeParts           Time constituents array.
 * @param array<int> $sourceFractionSizes Source time constituants ranges.
 * @param array<int> $targetFractionSizes Target time constituants ranges.
 * 
 * @return array<int>
 */
public function convertTimeWithLowerUnityCountRatio(array $timeParts, array $sourceFractionSizes, array $targetFractionSizes)
{
    $count = $this->getLowerUnityCountFromTime($timeParts, $sourceFractionSizes);

    // Now we multiply the count by the total units per day of the target
    //    format, then divide by the total units per date of the source
    //    format, so we only have one division, one transformation to float,
    //    so only one "float imprecision" issue.
    $count = ($count * array_product($targetFractionSizes))
        / array_product($targetFractionSizes)
    ;

    return $this->getTimeFromLowerUnityCount($count, $targetFractionSizes);
}

/**
 * Converts a "Time" (represented by an array of each of its constituents)
 *     into the lowest of its defined units (usefull if you want, for
 *     instance, to convert a [h,m,s,u] into seconds)
 * 
 * @param array<int> $timeParts     Time constituents array.
 * @param array<int> $fractionSizes Time constituants ranges.
 *
 * @return integer
 */
public function getLowerUnityCountFromTime(array $timeParts, array $fractionSizes)
{
    $len = count($fractionSizes);
    $res = 0;

    for ($i=0; $i < $len; $i++) {
        $part = isset($timeParts[$i]) ? $timeParts[$i] : 0;
        $res = $res * $fractionSizes[$i] + $part;
    }

    return $res;
}

/**
 * Convert a "lowest unity count" time representation to an array of
 *     constituents.
 *
 * @param integer $count         Lowest unity count.
 * @param array   $fractionSizes Time constituants ranges.
 *
 * @return array
 */
public function getTimeFromLowerUnityCount($count, array $fractionSizes)
{
    $len = count($fractionSizes);
    $res = array_fill(0, $len, 0);

    for ($i=$len - 1; $i > -1 ; $i--) { 
        $res[$i] = $count % $fractionSizes[$i];
        $count = intval($count / $fractionSizes[$i]);
    }

    return $res;
}


// Example

$time = convertTimeWithLowerUnityCountRatio(
    [12,0,0,0], // 12:00:00 and 0 microseconds
    [24, 60, 60, 1000000], // standard duodecimal time format
    [10, 100, 100, 1000000], // egyptian/revolutionary decimal format
);

?>
```

Misc
-----

Je suis tombé cette semaine sur ce repository alors que je recommençais à bidouiller ma mini-lib de calendrier révolutionnaire en PHP. Visiblement, ça fait un an que ce bout de code est sur mon smartphone aussi. Du coup, je me suis permis d'adapter ton code pour implémenter les méthodes de conversions (bon, j'ai fait que Romme), en citant bien entendu la source.

Ca se passe [par ici](https://github.com/popy-dev/popy-republican-calendar) si ça t'intéresse, ou si tu peux poster une issue pour réclamer plus d'enluminures autour de ton nom/repository.

**Comment by caarmen** [comment]
Many thanks for the investigation on improving the time conversion precision :)
I haven't dug into the code yet, but I'll take a look when I get a chance.

Currently I only use this library in an Android widget, and in that widget by default the time isn't displayed, and if the user does opt to show the time, the seconds aren't displayed. I think they used to be, but I removed the seconds display as it was a performance issue on Android. Or maybe there was a limitation preventing updating the widget every second. It was quite a long time ago :)

Merci et bonne continuation en PHP :)

**Comment by popy-dev** [comment]
> Many thanks for the investigation on improving the time conversion precision :)

I also noticed more recently than your VON_MADLER method is not a VON_MALDER. I'll probably create another issue soon :)

**Comment by caarmen** [comment]
#20 improved the precision of seconds conversion by using `roundToInt()` instead of `toInt()`.
