### ISSUE TITLE
Only one minor language error

### ISSUE THREAD

**Issue by DvP17** [caarmen/french-revolutionary-calendar#21]
First of all, this is a great app! Thank you very much for creating it!

In the german translation there should be written for Prairial "Wiesenmonat" instead of "Weisenmonat" (the last one means in german the month of the wise people instead of the correct translation month of grasland).

Furthermore, it would be great if you could also create a 4x1 widget!

Thank you very much!

**Comment by caarmen** [comment]
Hi @DvP17,

Thanks for reporting this spelling mistake!  It's been corrected in version 1.8.2.  I'll be publishing a new version of the Android app with this fix, shortly.

For more discussion on a 4x1 widget, please open an issue on the android app project: https://github.com/caarmen/FRCAndroidWidget

Cheers.
